class User :
    def __init__(self) :
        self.__id = None
        self.__firs_tname = None
        self.__last_name = None
        self.__email = None
        self.__gender = None
        self.__password = None
        self.__date_registered = None
        self.__dob = None
        self.__educational_background = None
